refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    filters:
      - kind: threshold
        level: debug # Log level for console
    encoder:
      pattern: "{({d(%Y-%m-%d %H:%M:%S)} {h({l})}):<25} - {m}{n}"

  file:
    kind: rolling_file
    filters:
      - kind: threshold
        level: trace # Log level for file
    encoder:
      pattern: "{({d(%Y-%m-%d %H:%M:%S)} {h({l})}):<25} - {m}{n}"
    path: "config/qbit_controller.log"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10485760 # 10 MB
      roller:
        kind: fixed_window
        pattern: "config/qbit_controller.{}.log"
        base: 1
        count: 5

root:
  level: trace
  appenders:
    - stdout
    - file
